const C='summerhouse-v142-webp';
const F=['./','index.html','room1.webp','kitchen-room2.webp','outside.webp','lake.webp','cove.webp','cove-end.webp','forest.webp','forest-end.webp','forest-end-set.webp','forest-end-eve.webp','forest-end-nt.webp','burrow.webp','fishing.webp','forest-pm.webp','forest-set.webp','forest-eve.webp','forest-nt.webp','fsign-sil.webp','fsign-face.webp','cend-pm.webp','cend-set.webp','cend-eve.webp','cend-tw.webp','cend-nt.webp','cove-pm.webp','cove-set.webp','cove-eve.webp','cove-tw.webp','cove-nt.webp','garden.webp','garden-set.webp','garden-eve.webp','garden-nt.webp','garden-n2.webp','sign-sil.webp','sign-face.webp','osign-sil.webp','osign-face.webp','outside-pm.webp','outside-set.webp','outside-eve.webp','outside-tw.webp','outside-nt.webp','bath.webp','bathtub.webp','bathtub-p.webp','wash-ball.webp','wash-body.webp','wash-shampoo.webp','wash-shower.webp','wash-shower-on.webp','wash-bubbles.webp','kitchen-sunset.webp','kitchen-dusk.webp','kitchen-midnight.webp','kitchen-twilight.webp','kitchen-night.webp','room-afternoon.webp','room-sunset.webp','room-dusk.webp','room-twilight.webp','room-night.webp','room-latenight.webp','room-midnight.webp','fan-night.webp','fan-twilight.webp','fan-room1.webp','fan-pm.webp','fan-sunset.webp','fan-dusk.webp','curtain-left.webp','curtain-right.webp','chiikawa.webp','chiikawa-open.webp','chiikawa-blink.webp','chiikawa-blink-open.webp','chiikawa-hurt1.webp','chiikawa-hurt2.webp','chiikawa-surprise-red.webp','chiikawa-shy-a.webp','chiikawa-shy-b.webp','berry.woff','bgm-s.mp3','ambient-s.mp3','ambient-eve-s.mp3','fan-intro2-s.mp3','fan-loop2-s.mp3','fan-fo1-s.mp3','fan-fo2-s.mp3','fan-fo3-s.mp3','hurt-s.mp3','hit1-s.mp3','sing1-s.mp3','hsing-s.mp3','surprise-s.mp3','knock-s.mp3','knock-k.mp3','step-s.mp3','step-k.mp3','face-chiikawa.webp','face-hachiware.webp','face-usagi.webp','hachiware-peek.webp','usagi-peek.webp','usagi-open.webp','hachi-come-s.mp3','hachi-live-s.mp3','usagi-hint-s.mp3','usagi-arrive-s.mp3','hachiware-open.webp','hachiware-blink.webp','hachiware-blink-open.webp','fish-get.webp','fish-pose.webp','book-icon.webp','book-cover.webp','book-open.webp','book-flip1.webp','book-flip2.webp','book-flip3.webp','book-flip4.webp','book-flip5.webp','manifest.json','icon-192.png','icon-512.png','book-fx.webp','fishd-01.webp','fishd-02.webp','fishd-03.webp','fishd-04.webp','fishd-05.webp','fishd-06.webp','fishd-07.webp','fishd-08.webp','fishd-09.webp','fishd-10.webp','fishd-11.webp','fishd-12.webp','fishd-13.webp','fishd-14.webp','fishd-15.webp','fishd-16.webp','fishd-17.webp','fishd-18.webp','fishd-19.webp','fishd-20.webp','fishc-01.webp','fishc-02.webp','fishc-03.webp','fishc-04.webp','fishc-05.webp','fishc-06.webp','fishc-07.webp','fishc-08.webp','fishc-09.webp','fishc-10.webp','fishc-11.webp','fishc-12.webp','fishc-13.webp','fishc-14.webp','fishc-15.webp','fishc-16.webp','fishc-17.webp','fishc-18.webp','fishc-19.webp','fishc-20.webp'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(F)));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(n=>n!==C).map(n=>caches.delete(n)))));self.clients.claim()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;
  // 아이폰은 오디오를 Range 요청으로 가져와서, 캐시에서도 206 응답으로 잘라서 줘야 해요
  if(e.request.headers.has('range')){e.respondWith(caches.match(e.request.url).then(r=>{if(!r)return fetch(e.request);return r.arrayBuffer().then(b=>{const m=/bytes=(\d+)-(\d*)/.exec(e.request.headers.get('range'))||[0,0,''];const s=+m[1],n=m[2]?Math.min(+m[2],b.byteLength-1):b.byteLength-1;return new Response(b.slice(s,n+1),{status:206,headers:{'Content-Type':r.headers.get('Content-Type')||'audio/mpeg','Content-Range':'bytes '+s+'-'+n+'/'+b.byteLength,'Content-Length':String(n-s+1)}})})}));return}
  // [성능] 그림·소리 같은 큰 파일은 캐시에 있으면 바로 쓰고(매번 다시 받아 덮어쓰지 않음), 페이지/스크립트만 최신본을 먼저 확인해요
  {const u=new URL(e.request.url),big=u.origin===location.origin&&/\.(png|jpe?g|mp3|woff2?)$/i.test(u.pathname);
   if(big){e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(res=>{if(res&&res.ok){const cp=res.clone();caches.open(C).then(c=>c.put(e.request,cp))}return res})));return}}
  e.respondWith(fetch(e.request).then(res=>{if(res&&res.ok&&new URL(e.request.url).origin===location.origin){const cp=res.clone();caches.open(C).then(c=>c.put(e.request,cp))}return res}).catch(()=>caches.match(e.request)))});
